<HTML>
  <HEAD>
    <TITLE>asio Reference: Effect of exceptions thrown from handlers</TITLE>
    <LINK HREF="asio.css" REL="stylesheet" TYPE="text/css">
    <LINK HREF="tabs.css" REL="stylesheet" TYPE="text/css">
  </HEAD>
  <BODY BGCOLOR="#FFFFFF">
    <DIV CLASS="qindex">
      <TABLE BORDER="0" WIDTH="100%">
        <TR>
          <TD ALIGN="LEFT">
            <B>asio 0.3.8rc1</B>
          </TD>
          <TD ALIGN="RIGHT">
            <A CLASS="qindex" HREF="../index.html">Home</A> |
            <A CLASS="qindex" HREF="../reference/index.html">Reference</A> |
            <A CLASS="qindex" HREF="../tutorial/index.html">Tutorial</A> |
            <A CLASS="qindex" HREF="../examples/index.html">Examples</A> |
            <A CLASS="qindex" HREF="../design/index.html">Design</A>
          </TD>
        </TR>
      </TABLE>
    </DIV>
    <DIV CLASS="qindex">
      <TABLE BORDER="0" WIDTH="100%">
        <TR>
          <TD ALIGN="LEFT">
            <B>Reference</B>
          </TD>
          <TD ALIGN="RIGHT">
            <A CLASS="qindex" HREF="hierarchy.html">Class Hierarchy</A> |
            <A CLASS="qindex" HREF="classes.html">Class Index</A> |
            <A CLASS="qindex" HREF="functions.html">Member Index</A>
          </TD>
        </TR>
      </TABLE>
    </DIV>
<!-- Generated by Doxygen 1.5.1 -->
<h1><a class="anchor" name="io_service_handler_exception">Effect of exceptions thrown from handlers</a></h1>If an exception is thrown from a handler, the exception is allowed to propagate through the throwing thread's invocation of <a class="el" href="a00032.html#c84bed0d1dd061bc71010ba1228439da">asio::io_service::run()</a>, <a class="el" href="a00032.html#a83c06ec5cc7bde25c64d89530998408">asio::io_service::run_one()</a>, <a class="el" href="a00032.html#fcc99e506862edaf34ac124c0e7f0242">asio::io_service::poll()</a> or <a class="el" href="a00032.html#cbdbe60a4582f7f77f5bdb85d4e76013">asio::io_service::poll_one()</a>. No other threads that are calling any of these functions are affected. It is then the responsibility of the application to catch the exception.<p>
After the exception has been caught, the <a class="el" href="a00032.html#c84bed0d1dd061bc71010ba1228439da">asio::io_service::run()</a>, <a class="el" href="a00032.html#a83c06ec5cc7bde25c64d89530998408">asio::io_service::run_one()</a>, <a class="el" href="a00032.html#fcc99e506862edaf34ac124c0e7f0242">asio::io_service::poll()</a> or <a class="el" href="a00032.html#cbdbe60a4582f7f77f5bdb85d4e76013">asio::io_service::poll_one()</a> call may be restarted <em>without</em> the need for an intervening call to <a class="el" href="a00032.html#28a4283881eba54d415409ad604384f8">asio::io_service::reset()</a>. This allows the thread to rejoin the io_service's thread pool without impacting any other threads in the pool.<p>
<dl class="user" compact><dt><b>Example</b></dt><dd><div class="fragment"><pre class="fragment"> <a class="code" href="a00032.html">asio::io_service</a> io_service;
 ...
 <span class="keywordflow">for</span> (;;)
 {
   <span class="keywordflow">try</span>
   {
     io_service.<a class="code" href="a00032.html#c84bed0d1dd061bc71010ba1228439da">run</a>();
     <span class="keywordflow">break</span>; <span class="comment">// run() exited normally</span>
   }
   <span class="keywordflow">catch</span> (my_exception&amp; e)
   {
     <span class="comment">// Deal with exception as appropriate.</span>
   }
 }
</pre></div> </dd></dl>
    <DIV CLASS="qindex">
      <TABLE BORDER="0" WIDTH="100%">
        <TR>
          <TD ALIGN="LEFT">
            <B>asio 0.3.8rc1</B>
          </TD>
          <TD ALIGN="RIGHT">
            <A CLASS="qindex" HREF="../index.html">Home</A> |
            <A CLASS="qindex" HREF="../reference/index.html">Reference</A> |
            <A CLASS="qindex" HREF="../tutorial/index.html">Tutorial</A> |
            <A CLASS="qindex" HREF="../examples/index.html">Examples</A> |
            <A CLASS="qindex" HREF="../design/index.html">Design</A>
          </TD>
        </TR>
      </TABLE>
    </DIV>
  </BODY>
</HTML>
